//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates and Needle so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com and https://github.com/uber/needle
//

import UIKit

protocol ___VARIABLE_sceneName___PresentationLogic {
  // Something
  
}

class ___VARIABLE_sceneName___Presenter: ___VARIABLE_sceneName___PresentationLogic {
  var viewController: ___VARIABLE_sceneName___DisplayLogic
  init(viewController: ___VARIABLE_sceneName___DisplayLogic) {
      self.viewController = viewController
  }
    
  // MARK: Do something
  
}
