//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___VARIABLE_organizationName___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates and Needle so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com and https://github.com/uber/needle
//

import UIKit

protocol ___VARIABLE_sceneName___BusinessLogic {
  // doSomething
}

protocol ___VARIABLE_sceneName___DataStore {
  //var name: String { get set }
}

class ___VARIABLE_sceneName___Interactor: ___VARIABLE_sceneName___BusinessLogic, ___VARIABLE_sceneName___DataStore {
  var presenter: ___VARIABLE_sceneName___PresentationLogic?
  init(presenter: ___VARIABLE_sceneName___PresentationLogic) {
      self.presenter = presenter
  }
}
