//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates and Needle so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com and https://github.com/uber/needle
//

import UIKit

@objc protocol ___VARIABLE_sceneName___RoutingLogic {
  // routeToSomewhere
}

protocol ___VARIABLE_sceneName___DataPassing {
  var dataStore: ___VARIABLE_sceneName___DataStore { get }
}

class ___VARIABLE_sceneName___Router: NSObject, ___VARIABLE_sceneName___RoutingLogic, ___VARIABLE_sceneName___DataPassing {
  var dataStore: ___VARIABLE_sceneName___DataStore
  init(dataStore: ___VARIABLE_sceneName___DataStore) {
      self.dataStore = dataStore
  }
  // MARK: Routing

  // MARK: Navigation
  
  // MARK: Passing data
  
}
