//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates and Needle so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com and https://github.com/uber/needle
//

import UIKit
import NeedleFoundation

protocol ___VARIABLE_sceneName___Dependency: Dependency {
  // doSomething
}

protocol ___VARIABLE_sceneName___Builder {
    var viewController: ___VARIABLE_sceneName___ViewController { get }
}

class ___VARIABLE_sceneName___Component: Component<___VARIABLE_sceneName___Dependency>, ___VARIABLE_sceneName___Builder {
    var viewController: ___VARIABLE_sceneName___ViewController {
        let viewController = ___VARIABLE_sceneName___ViewController()
        let presenter = ___VARIABLE_sceneName___Presenter(viewController: viewController)
        let interactor = ___VARIABLE_sceneName___Interactor(presenter: presenter)
        let router = ___VARIABLE_sceneName___Router(dataStore: interactor)
        viewController.inject(interactor: interactor, router: router)
        return viewController
    }
}
